# Generated by Django 4.2.4 on 2023-08-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='name')),
                ('pwd', models.CharField(max_length=64, verbose_name='password')),
                ('mobile', models.CharField(max_length=64, verbose_name='mobile phone')),
                ('email', models.CharField(max_length=32, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='name')),
                ('pwd', models.CharField(max_length=64, verbose_name='password')),
                ('mobile', models.CharField(max_length=64, verbose_name='mobile phone')),
                ('email', models.CharField(max_length=32, verbose_name='email')),
                ('age', models.IntegerField(verbose_name='age')),
                ('subscribe', models.BooleanField(default=False)),
                ('level', models.IntegerField(verbose_name='level')),
            ],
        ),
    ]
