# Generated by Django 4.2.4 on 2023-08-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userinfo_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='level',
            field=models.IntegerField(default=1, verbose_name='level'),
        ),
    ]
