# Generated by Django 4.2.4 on 2023-08-14 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='level_lable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level1', models.CharField(max_length=1000, verbose_name='level1')),
                ('level2', models.CharField(max_length=1000, verbose_name='level2')),
            ],
        ),
        migrations.CreateModel(
            name='NewCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('level1', models.CharField(max_length=100, verbose_name='level1')),
                ('level2', models.CharField(max_length=100, verbose_name='level2')),
                ('contents', models.CharField(max_length=3000, verbose_name='what_area')),
                ('contents1', models.CharField(max_length=3000, verbose_name='what_area')),
                ('source', models.CharField(blank=True, max_length=300, null=True, verbose_name='source_area')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('question1', models.CharField(max_length=1000, verbose_name='question1')),
                ('q1_o1', models.CharField(max_length=1000, verbose_name='question1')),
                ('q1_o2', models.CharField(max_length=1000, verbose_name='question1')),
                ('q1_o3', models.CharField(max_length=1000, verbose_name='question1')),
                ('answer1', models.CharField(max_length=1000, verbose_name='answer1')),
                ('question2', models.CharField(max_length=1000, verbose_name='question2')),
                ('q2_o1', models.CharField(max_length=1000, verbose_name='question1')),
                ('q2_o2', models.CharField(max_length=1000, verbose_name='question1')),
                ('q2_o3', models.CharField(max_length=1000, verbose_name='question1')),
                ('answer2', models.CharField(max_length=1000, verbose_name='answer2')),
                ('question3', models.CharField(max_length=1000, verbose_name='question3')),
                ('q3_o1', models.CharField(max_length=1000, verbose_name='question1')),
                ('q3_o2', models.CharField(max_length=1000, verbose_name='question1')),
                ('q3_o3', models.CharField(max_length=1000, verbose_name='question1')),
                ('answer3', models.CharField(max_length=1000, verbose_name='answer3')),
            ],
        ),
        migrations.CreateModel(
            name='NewContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='title')),
                ('classification', models.CharField(max_length=500, verbose_name='classification')),
                ('what_area', models.CharField(max_length=3000, verbose_name='what_area')),
                ('how_area', models.CharField(blank=True, max_length=3000, null=True, verbose_name='how_area')),
                ('example', models.CharField(blank=True, max_length=3000, null=True, verbose_name='example_area')),
                ('source', models.CharField(blank=True, max_length=2000, null=True, verbose_name='source_area')),
                ('try_area', models.CharField(blank=True, max_length=3000, null=True, verbose_name='try_area')),
                ('image_name', models.CharField(blank=True, max_length=200)),
                ('image_data', models.ImageField(default='user_image.jpg', upload_to='user_images')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userinfo', verbose_name='author')),
            ],
        ),
    ]
